language: node_js
node_js:
  - 6
  - 7
  - 8
before_install:
  - wget abyz.me.uk/rpi/pigpio/pigpio.zip
  - unzip pigpio.zip
  - make -C PIGPIO
  - sudo make install -C PIGPIO
install:
  - npm install
script:
  - npm run build
  - npm run lint
deploy:
  provider: npm
  email: "rafaelquines@gmail.com"
  api_key: "734e57f0-a62f-48ec-894e-f78e24966bf0"
  on:
    tags: true