language: node_js
node_js:
  - 6
  - 7
  - 8
before_install:
  - wget abyz.me.uk/rpi/pigpio/pigpio.zip
  - unzip pigpio.zip
  - make -C PIGPIO
  - sudo make install -C PIGPIO
script:
  - npm install
  - npm run build